Task_02 Inverted index
wkdjgf534/go_course_4 pull request #2
Opened 2023-06-30 21:17 UTC by wkdjgf534

2023-07-05 12:55 UTC, DmitriyVTitov requested changes
Очень важно обрабатывать ошибки всегда!

2023-07-05 12:55 UTC, DmitriyVTitov commented on homework-02/cmd/gosearch/gosearh.go
> +	"go-course-4/homework-02/pkg/crawler"
`homework-02` -> `homework-03`
всё таки это третье задание

2023-07-05 12:55 UTC, DmitriyVTitov commented on homework-02/cmd/gosearch/gosearh.go
> +)
Глобальные константы вообще не очень хорошо. А уж если они используются по одному разу, так тем более )

2023-07-05 12:55 UTC, DmitriyVTitov commented on homework-02/cmd/gosearch/gosearh.go
> +	}
Ошибка сканирования не обработана. Должно быть действие, а у вас программа продолжает работать как ни в чем не бывало.
Это очень важно!

2023-07-06 07:43 UTC, wkdjgf534 commented
Добавил errors и простую передачу ошибки из crawler. Теперь видно ошибки сети.

![Screen Shot 2023-07-06 at 09 38 44](https://github.com/wkdjgf534/go_course_4/assets/22746601/9a75cbc5-516e-4255-8185-87938b055c2a)

2023-07-08 05:12 UTC, DmitriyVTitov approved these changes
Потренируйтесь работать с ошибками. Почитайте статьи по ним.

2023-07-08 05:12 UTC, DmitriyVTitov commented on homework-03/cmd/gosearch/gosearh.go
> +	}
Вот тут ошибка не обработана!

2023-07-08 05:12 UTC, DmitriyVTitov commented on homework-03/pkg/index/index.go
> +	return ids, nil
Ошибка тут нелогична. В смысле, что если ничего не найдено, то достаточно вернуть пустой массив.

2023-07-08 05:12 UTC, DmitriyVTitov commented on homework-03/pkg/index/index.go
> +	}
Здесь тоже ошибка лишняя. Нет документов на входе - ну и ладно, ошибка-то в чём?

2023-07-09 18:16 UTC, merged